name: 'Deploy pipeline'

on:
  # automatic trigger on push to specific branches/tags
  push:
    branches:
      - develop
      - release/**
    tags:
      - release/**

  # manual trigger
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: choice
        required: true
        options:
          - dev
          - uat
          - prod
      ref:
        description: 'Branch/tag to deploy ("release/x" is required for prod!)'
        type: string
        required: true
        default: 'develop'

permissions:
  id-token: write # required for OIDC authentication
  contents: write # ensures the token can write repository content

env:
  NODE_VERSION: '18.x'
  TARGET_ENV: 'dev'
  GH_ASSUME_ROLE: 'GitHubActionsAssumeRole'
  PROD_AWS_ACCOUNT_ID: '173381260310'
  UAT_AWS_ACCOUNT_ID: '166669426596'
  DEV_AWS_ACCOUNT_ID: '166669426596'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: >-
            ${{ github.event.inputs.ref || github.ref_name }}

      - name: Validate Deployment Eligibility
        run: |
          EVENT_NAME="${{ github.event_name }}"
          TARGET_ENV="${{ github.event.inputs.environment }}"
          DEPLOY_REF="${{ github.event.inputs.ref }}"
          GIT_REF="${{ github.ref_name }}"

          # Target branch (fallback to git ref from a push event)
          if [[ ! -z "$DEPLOY_REF" ]]; then
            DEPLOY_BRANCH="$DEPLOY_REF"
          else
            DEPLOY_BRANCH="$GIT_REF"
          fi

          # Default environment selection for push/merge events
          if [[ "$EVENT_NAME" == "push" ]]; then
            if [[ "$DEPLOY_BRANCH" == "develop" ]]; then
              TARGET_ENV="dev"
            elif [[ "$DEPLOY_BRANCH" =~ ^release/ ]]; then
              TARGET_ENV="uat"
            fi
          fi

          # Production environment additional validation rules - no automatic deploys
          if [[ "$EVENT_NAME" == "workflow_dispatch" && "$TARGET_ENV" == "prod" ]]; then
            if [[ ! "$DEPLOY_BRANCH" =~ ^release/ ]]; then
              echo "ERROR: For 'prod', branch/tag must match release/** format!"
              exit 1
            fi
          fi

          echo "Deploying branch '${DEPLOY_BRANCH}' to '${TARGET_ENV}' environment.."
          echo "TARGET_ENV=$TARGET_ENV" >> $GITHUB_ENV
          echo "DEPLOY_BRANCH=$DEPLOY_BRANCH" >> $GITHUB_ENV

      - name: Initial Setup
        uses: ./.github/actions/initial-setup
        with:
          node_version: ${{ env.NODE_VERSION }}
          environment: ${{ env.TARGET_ENV }}
          prod_aws_account_id: ${{ env.PROD_AWS_ACCOUNT_ID }}
          uat_aws_account_id: ${{ env.UAT_AWS_ACCOUNT_ID }}
          dev_aws_account_id: ${{ env.DEV_AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ env.GH_ASSUME_ROLE }}

      - name: Preparations and Quality Gates
        uses: ./.github/actions/install-quality-gates-setup

      - name: Run Build
        run: npm run build

      - name: Deploy Build And Reset CloudFront Cache
        run: |
          echo "S3 deploy..."
          ls -al build/

          echo "CDN cache reset..."
          aws --version
          aws sts get-caller-identity

