name: 'initial-setup'
description: 'Sets up dependencies, configures AWS credentials'

inputs:
  aws_account_id:
    required: true
    description: 'AWS Account ID'
  gh_assume_role:
    required: true
    description: 'GitHub Assume Role ARN'
  deploy_role:
    required: true
    description: 'Elevated deployment role'
  environment:
    required: true
    description: 'Environment name'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js from .nvmrc
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Setup ReviewDog
      id: setup-reviewdog
      uses: reviewdog/action-setup@v1.5.0
      with:
        reviewdog_version: latest

    - name: Configure AWS credentials
      id: configure-aws-credentials-oidc
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.gh_assume_role }}
        aws-region: us-east-1 # STS default region

    - name: test identity 1
      shell: bash
      run: |
        aws sts get-caller-identity

    - name: Configure deployment role AWS Credentials
      id: configure-aws-credentials-deploy
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.deploy_role }}
        role-session-name: github-fv-frontend
        role-chaining: true

    - name: test identity 2
      shell: bash
      run: |
        aws sts get-caller-identity
